# For more infiormation https://github.com/realm/SwiftLint/blob/master/README.md
# To validate .swiftlint.yml file http://www.yamllint.com
custom_rules:
  discouraged_image_literal:
    name: "Discouraged Image Literal"
    regex: "#imageLiteral"
    message: "Please use UIImage(named:) instead"
    severity: error

disabled_rules:
    - type_name
    - line_length
    - blanket_disable_command
